# Config File

adapters:
  ILLUMINACLIP:NexteraPE-PE.fa:2:30:10:8:true

bt2_genome:
  /home/groups/hoolock2/u0/genomes/ucsc/mm10/indexes/bowtie2/mm10

gtf:
  /home/groups/hoolock2/u0/genomes/ucsc/mm10/annotation/mm10.ncbiRefSeq.gtf

mt_chr:
  chrM

effective_genome_size:
  2652783500

macs2_genome:
  mm

contrasts:
  - Got2KD_vs_Ctrl

analysis_method:
  DBA_EDGER

min_overlap:
  2

fdr_cutoff:
  0.05

data_source:
  mm10

organism:
  Mus_musculus
